noobaid/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('default.url')),
]

default/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver

LEVELS=(
    ('E','Entry Level (0 - 2 yrs)'),
    ('M','Mid-level (3 - 4 yrs)'),
)

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    instituition=models.CharField(max_length=354,null=True,default="")
    avatar=models.ImageField(upload_to='avatars')
    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance,)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()
    def __str__(self):
        return self.user.username+ " : " +self.user.first_name + self.user.last_name



class Job(models.Model):
    title=models.CharField(max_length=254)
    description=models.TextField()
    location=models.CharField(max_length=254,default='')
    job_descriptionlink=models.URLField(null=True,blank=True)
    hirer=models.CharField(max_length=254, default='Linuxjobber')
    level=models.CharField(max_length=2,default='E',choices=LEVELS)
    updated_on=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class JobApplication(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    job=models.ForeignKey(Job,on_delete=models.CASCADE,null=True,blank=True)
    resume=models.FileField(upload_to='job_resumes')
    updated_on=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.job.title + ' ' + self.user.username
# Todo Design the model Appropriately

default/forms.py
from django import forms
from django.contrib.auth.models import User

from default.models import Profile, JobApplication


class UserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','password','email','first_name','last_name']
        widgets={
            'username':forms.EmailInput(attrs={'class':'form-control','placeholder':'email','noautocomplete':''}),
            'first_name':forms.EmailInput(attrs={'class':'form-control','placeholder':'First Name','noautocomplete':''}),
            'last_name':forms.EmailInput(attrs={'class':'form-control','placeholder':'LastName','noautocomplete':''}),
            'password' : forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password (6 - 15 Characters)'}),
        }

class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['instituition']
        widgets={

            # 'username':forms.EmailInput(attrs={'class':'form-control','placeholder':'email','noautocomplete':''}),
            # 'password' : forms.PasswordInput(attrs={'class':'form-control','placeholder':'password'}),
            # 'email' : forms.TextInput(attrs={'class':'form-control','placeholder':'email'}),
            'instituition' : forms.TextInput(attrs={'class':'form-control','placeholder':'instituition'})


        }

class JobApplicationForm(forms.ModelForm):
    class Meta:
        model=JobApplication
        exclude=['updated_on']
        widgets={
            'resume':forms.FileInput(attrs={'class':'input file'})
        }

default/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
# Create your views here.
from django.template.response import TemplateResponse

from default.forms import UserForm, ProfileForm, JobApplicationForm
from default.models import Profile, Job, JobApplication
from noobaid import settings

global next_page
def index(request):
    return TemplateResponse(request,'default/index.html')


def login_user(request):
    if request.GET:
        global next_page
        next_page=request.GET.get('next')
        print('This is next column')

    error_message = ""
    if request.user.is_authenticated:
        return redirect("default:index")
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        try:
            user = User.objects.get(username=username)
            if not user.is_active:
                error_message="Sorry, account disabled, contact the administrator"
            if not error_message:
                if check_password(password, user.password):
                    a=authenticate(username=username,password=password)
                    login(request,user)
                else:
                    error_message = "Invalid Password"
        except User.DoesNotExist:
            error_message = "Sorry, No account exists with that username"

        finally:
            if error_message:
                return TemplateResponse(request, "registration/login.html", {"error_message": error_message})
            if next_page:
                return HttpResponseRedirect(next_page)
            else:
                return redirect("default:index")
    else:
        return TemplateResponse(request, "registration/login.html", {"error_message": error_message})


def logout_user(request):
    logout(request)
    return redirect("default:login")



def signup(request):
    _form = UserForm(request.POST or None)
    _pform = ProfileForm(request.POST or None)
    if request.method == "POST":
        user = User()
        profile = Profile()
        form = UserForm(request.POST, instance=user)
        pform = ProfileForm(request.POST, instance=profile)
        if form.is_valid() and pform.is_valid():
            new_user = form.save(commit=False)
            new_user.email = form.cleaned_data['username']
            new_user.save()
            new_user.set_password(user.password)
            new_user.save()
            p= Profile.objects.get(user=new_user)
            p.instituition=pform.cleaned_data['instituition']
            p.save()
            logout(request)
            return TemplateResponse(request,'registration/login.html',{'error_message':'Account Created, log in here'})
        else:
            return TemplateResponse(request, 'registration/signup.html', {"userform": _form,'profileform':_pform})
    else:
        return TemplateResponse(request, 'registration/signup.html', {"userform": _form,'profileform':_pform})

def job_list(request):
    job_list = Job.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(job_list, 10)
    try:
        jobs = paginator.page(page)
    except PageNotAnInteger:
        jobs = paginator.page(1)
    except EmptyPage:
        jobs = paginator.page(paginator.num_pages)

    return TemplateResponse(request, 'default/joblist.html', {'jobs': jobs})

@login_required
def job_detail(request,job_id):
    context={}
    try:
        job=Job.objects.get(pk=job_id)
    except Job.DoesNotExist:

        return TemplateResponse(request,'default/page404.html')
    context.update({'job':job})



    return TemplateResponse(request,'default/job_detail.html',context)

@login_required
def job_apply(request,job_id):
    job=get_object_or_404(Job,pk=job_id)
    form=JobApplicationForm(request.POST or None,request.FILES or None)

    if request.method=='POST':
        if form.is_valid():
            f=form.save(commit=False)
            f.job=job
            f.user=get_object_or_404(User,username=request.user.username)
            f.save()
            return redirect('default:success')
        else:
            return TemplateResponse(request,'default/job_apply.html',{'job':job,'form':form})
    else:
        return TemplateResponse(request,'default/job_apply.html',{'job':job,'form':form})


def success(request):
    return TemplateResponse(request,'default/success.html')

def email(request):
    subject = 'Thank you for registering to our site'
    message = ' it  means a world to us '
    recipient_list = ['azmayowa@gmail.com',]
    send_mail(subject=subject, message=message, recipient_list=recipient_list )
    return HttpResponse('sent')

default/templates/default/index.html
{% extends 'default/base.html' %}


{% block content %}
    <!-- start of banner -->
    <section class="homebanner text-center">
        <div class="homebanner_slide homepage-slider-box">
            <div class="flexslider">
                <ul class="slides">
                    <li>
                        <div class="flexcontent">
                            {% load static %}
                            <img src="{% static 'default/img/bannnerimg.jpg' %}" alt=""/>
                            <div class="homebanner_content">
                                <div class="container">
                                    <div class="box-demand">JUNIOR & ENTRY LEVEL JOBS</div>
                                    <h1>Right balance between productivity and cost</h1>
                                    <p></p>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>

        </div>
    </section>
    <!-- end of banner -->
    <section class="help-expert-box">
        <div class="help-expert-box-inner">
            <div class="container">
                <div class="col-md-6">
                    <div class="help-expert-content-box bg-box-one">
                        <h3>I want to employ a graduate</h3>
                        <p>Find graduating students with skill set <span> that match your company's I.T. needs</span>
                        </p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="help-expert-content-box bg-box-two">
                        <h3>I am graduating. I need a job</h3>
                        <p>Find employers that are looking for graduates<span> with your specific skill set</span></p>
                        <a href="{% url 'default:job-list' %}" class="green-box-btn">Find a Job</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- end of lovely projects -->
    <!-- lovely projects -->
    <!-- lovely projects -->
    <section class="curatedpages text-center equal">
        <div class="container">
            <div class="curatedhead clearfix">
                <h2>Employer Path</h2>
                <p class="work-pera">All graduates are not the same. Some are hardworking and prepared while others are
                    not. <span>This platform is designed to help employers pick the right graduates</span></p>
            </div>
            <div class="how-it-work-box">
                <div class="col-sm-3">
                    <div class="how-it-work-box-inner">
                        <!--<img src="/images/icon-one-box.png">-->
                        {% load static %}
                        <img src="{% static 'default/img/icon-one-box.png' %}" alt=""/>
                        <h4>Specify the Position</h4>
                        <p>Know which position you would like to fill</p>
                    </div>
                </div>
                <div class="col-sm-3">{% load staticfiles %}
                    <div class="how-it-work-box-inner">

                        <img src="{% static 'default/img/icon-one-box-2.png' %}" alt=""/>
                        <h4>View By Skillsets</h4>
                        <p>View graduating students sorted by relevant skill set</p>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="how-it-work-box-inner">
                        <img src="{% static 'default/img/icon-one-box-3.png' %}" alt=""/>
                        <h4>Select and Interview</h4>
                        <p>Make your selection and interview candidates</p>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="how-it-work-box-inner">
                        <img src="{% static 'default/img/icon-one-box-4.png' %}" alt=""/>
                        <h4> Fill Your Opening</h4>
                        <p>Employ the candidate of your choice</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end of how to work it -->
    <section class="expert-working text-center equal">
        <div class="container">
            <h3 style="line-height: 40px;">Career Services <br/><br/>We support campus Career Service Centers in finding
                junior and entry level positions for their students through our partnership with local recruiters. Find
                out how our services can help improve your center's overall productivity now.</h3>


        </div>
    </section>
    <!-- testimonial -->
    <section class="curatedpages text-center equal">
        <div class="container">
            <div class="curatedhead clearfix">
                <h2>Student Testimonials</h2>
            </div>
            <div class="box-mid-width">
                <div class="col-sm-6">
                    <div class="testimonial-box-inner">
                        <p>"Browsing through open positions on noobaid.com helped me understand what employers are
                            really looking for. "</p>
                    </div>
                    <figure><img src="{% static 'default/img/testimonial-one.png' %}" alt=""/><h5>Ivan Herrera <span>Network Administration, A.A.S.</span>
                    </h5></figure>
                </div>
            </div>
            <div class="box-mid-width">
                <div class="col-sm-6">
                    <div class="testimonial-box-inner">
                        <p>"Computer Science field is very wide and I needed a mentor to guide me. Noobaid provided the
                            support I needed."</p>
                    </div>
                    <figure><img src="{% static 'default/img/testimonial-two.png' %}" alt=""/><h5>Suzzane Hamilton
                        <span>Computer Science, B.Sc.</span></h5></figure>
                </div>
            </div>
            <div class="box-mid-width">
                <div class="col-sm-6">
                    <div class="testimonial-box-inner">
                        <p>"I was able to network with working professionals and find solutions to some of the technical
                            problems I had."</p>
                    </div>
                    <figure><img src="{% static 'default/img/testimonial-three.png' %}" alt=""/><h5>Karl Gimble <span>Information Technology, A.A.S.</span>
                    </h5></figure>
                </div>
            </div>
            <div class="box-mid-width">
                <div class="col-sm-6">
                    <div class="testimonial-box-inner">
                        <p>"I found the junior and entry level positions on noobaid.com very useful because I had no
                            prior experience."</p>
                    </div>
                    <figure>
                        <div class="innerInnerImg"><img src="{% static 'default/img/david_ajao_headshot.png' %}"
                                                        alt=""/></div>
                        <h5>David Ajao <span>Computer Science, M.Sc.</span></h5>
                    </figure>
                </div>
            </div>
        </div>
    </section>
    <!-- testimonial End-->


    <section class="curatedpages text-center bg-lite-grey equal">
        <div class="container">
            <div class="curatedhead clearfix">
                <h2>Looking for a specific certification?</h2>
                <p class="work-pera">Work with students who already have the certification.</p>
            </div>

            <div class="col-sm-3">
                <div class="specific-service">
                    <a href=""><img src="{% static 'default/images/RHEL-logo1.png' %}" alt=""/></a>
                    <aside>
                        <p>I will dig into any RedHat error FREE for 5 mins</p>
                        <h5>Linux<span>System Administrator</span></h5>
                    </aside>
                </div>
            </div><!--col-sm-3-->

            <div class="col-sm-3">
                <div class="specific-service">
                    <a><img src="{% static 'default/images/oracle-new.jpg' %}" alt=""/></a>
                    <aside>
                        <p>I will Explain any PL/SQL Error FREE for 5 mins</p>
                        <h5>Database<span>Oracle DBA</span></h5>
                    </aside>
                </div>
            </div><!--col-sm-3-->
            <div class="col-sm-3">
                <div class="specific-service">
                    <a><img src="{% static 'default/images/aws1-new.png' %}" alt=""/></a>
                    <aside>
                        <p>I will provide AWS Support FREE for 5 mins</p>
                        <h5>AWS<span>Cloud Administrator</span></h5>
                    </aside>
                </div>
            </div><!--col-sm-3-->
            <div class="col-sm-3">
                <div class="specific-service">
                    <a><img src="{% static 'default/images/RHEL-logo1.png' %}" alt=""/></a>
                    <aside>
                        <p>I will dig into any RedHat error FREE for 5 mins</p>
                        <h5>Linux<span>System Administrator</span></h5>
                    </aside>
                </div>
            </div>
            <!--col-sm-3-->
        </div>
    </section>

    <!-- End here -->


{% endblock %}

default/templates/default/job_apply.html
{% extends 'default/base.html' %}


{% block content %}
    <section class="teachsetting" style="padding-bottom:40px;">
        <div class="container">
            <div class="regconfrimbox over-flow">
                <div class="confrimboxin bottomInput">
                    <h3 class="headdingformet">
                        <b style="font-size:25px;color:red;">Please upload your Resume to Apply for Job</b>

                    </h3>
                    <div class="backList">
                            <a href="{% url 'default:job-list' %}" class="btn greenbtn"
                               style="background: #fff none repeat scroll 0 0; border: 1px solid #1db95c;color: #1db95c;">&lt;
                                Back</a></div>
                    <div class="detailLeft fullWidth">
                        <div class="detailbox">
                            <div class="filesinner1">
                                <div class="col-sm-12 inputformet">
                                    <div class="row">
                                        <div class="input file">

                                            <div class="box fileSelect">
                                                <label id="buttonMain" for="id_resume" style="width:175px;">
                                                    Select your Resume - {{ form.errors }}
                                                </label>
                                                <form enctype="multipart/form-data" method="post" accept-charset="utf-8"
                                                      novalidate="novalidate" id="resumeform"
                                                      action="{% url 'default:job-apply' job.pk %}">
                                                    {% csrf_token %}
                                                    {{ form.resume }}


                                                    <button class="btn greenbtn" id="resumeupload"
                                                            style="float: left; height: 40px; margin-left :5px; width:110px; padding-top:8px;"
                                                            >Upload
                                                    </button>
                                                </form>
                                                <div>Only .doc,.docx and pdf resumes are supported</div>
                                                <div id="files_list"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

default/templates/default/job_detail.html
{% extends 'default/base.html' %}


{% block content %}
    <section class="teachbdy reg-confirm changebg">
		<div class="container">
			<div class="regconfrimbox over-flow">
				<div class="confrimboxin bottomInput">
					<h3 class="headdingformet">
						{{ job.title }}						<div class="backList">

							<a href="{% url 'default:job-list' %}" class="btn greenbtn" style="margin-top: 20px; background: #fff none repeat scroll 0 0; border: 1px solid #1db95c;color: #1db95c;">&lt; Back</a>
                        {% if job.hirer == 'Linuxjobber' %}

                        <a href="{% url 'default:job-apply' job.pk %}" class="btn greenbtn" style="margin-top: 20px;">Apply Now</a>
                        {% else %}
                        <a href="{{ job.job_descriptionlink }}" class="btn greenbtn" style="margin-top: 20px;">Apply Now</a>
                    {% endif %}
                    </div>
						<span>{{ job.hirer }} | {{ job.get_level_display }} | Location : {{ job.location }}</span>
						<span></span>
						<span>{{ job.updated_on|date:'r' }}</span>
					</h3>
					<div class="detailLeft fullWidth">
						<div class="detailbox">
							<div class="filesinner1">
								<p><strong>Job Description:</strong></p>
                             <p>{{ job.description|linebreaksbr    }}</p>


							</div>
						</div>
					</div>


						<div class="col-sm-12 inputformet">
							<div class="row">

                                {% if job.hirer == 'Linuxjobber' %}

                        <a href="{% url 'default:job-apply' job.pk %}" class="btn greenbtn" style="margin-top: 20px;">Apply Now</a>
                        {% else %}
                        <a href="{{ job.job_descriptionlink }}" class="btn greenbtn" style="margin-top: 20px;">Apply Now</a>
                    {% endif %}

								</div>
							</div>
                            <div class="headdingformet text-left">
                            <span>
                                Job Link : <a href="{{ job.job_descriptionlink|default:'#' }}">{{ job.job_descriptionlink|default:'None' }}</a>
                            </span>
                            </div>
                        </div>
                    </div>
                </div>



	</section>

{% endblock %}

default/templates/default/joblist.html
{% extends 'default/base.html' %}


{% block content %}

    <section class="teachbdy reg-confirm changebg">
        {% load static %}
        <div style="width: 100%; text-align: center; min-height: 230px; height: 100%; background: url('{% static 'default/img/img.png' %}') no-repeat; background-size: 100% 100%; background-color: black;">
            <span style="font-size: 45px; line-height: 170px; display: block; padding: 0px 0 5px 0;">Junior and Entry Level Jobs </span>

        </div>
        <div class="container">
            <div class="regconfrimbox over-flow">
                <div class="confrimboxin">
                    <!--                <h3 class="headdingformet allProblem">-->
                    <div class="searchLeft">
                        <div class="submit searchButton">
                            <a href="javascript:void(0)" title="Search">Search</a></div>
                        <div class="search_form hidden listProblem">
                            <form method="post" accept-charset="utf-8" id="searchForm"
                                  action="https://noobaid.com/jobportals?page=4">
                                <div class="input text">
                                    <!--<label for="title">Title</label>-->
                                    <div class="input text"><input type="text" name="title" id="title"
                                                                   placeholder="Search" value=""></div>
                                </div>
                                <div class="submit">
                                    <button class="search"><i class="glyphicon glyphicon-search"></i>
                                    </button>
                                </div>
                            </form>
                        </div>
                        <div class="submit hidden hideSearch">
                            <a href="javascript:void(0)" title="Search">Hide Search</a></div>
                    </div>
                    <!--                </h3>-->

                    <div class="tableSelect">
                        <div class="allProblems tableCls">
                            <ul>

                                {% for job in jobs %}
                                    <li>
                                        <div class="toptitleicon">
                                            <h2>
                                                <a href="{% url 'default:job-detail' job.pk %}">{{ job.title }}</a>
                                            </h2>

                                        </div>
                                        <div class="bottomIcons">
                                            <i class="glyphicon glyphicon-time"></i>
                                            <b>
                                                {{ job.updated_on|date:'r' }} | {{ job.hirer }} | {{ job.get_level_display }} | Location : {{ job.location }}
                                            </b>
                                        </div>
                                        <div>
                                            <p><strong>Job Requirements:</strong></p>

                                            <p>  {{ job.description|truncatewords:30 }}
                                                <a href="{% url 'default:job-detail' job.pk %}"
                                                            style="font-size:13px;color:#7E7989">See more</a>.... </p>
                                        </div>
                                    </li>
                                {% endfor %}

                            </ul>
                        </div>


                        <div class="rightpagination">
                            {% if jobs.has_other_pages %}
                                <ul class="pagination">
                                    {% if jobs.has_previous %}
                                        <li><a href="?page={{ jobs.previous_page_number }}">&laquo;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>&laquo;</span></li>
                                    {% endif %}
                                    {% for i in jobs.paginator.page_range %}
                                        {% if jobs.number == i %}
                                            <li class="active"><span>{{ i }}</span></li>
                                        {% else %}
                                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if jobs.has_next %}
                                        <li><a href="?page={{ jobs.next_page_number }}">&raquo;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>&raquo;</span></li>
                                    {% endif %}
                                </ul>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>

{% endblock %}

default/templates/default/page404.html
{% extends 'default/base.html' %}


{% block content %}

    <h1 class="">Page Not Found</h1>
    <h1 class="">Oops, Seems like you entered a wrong link</h1>
{% endblock %}

default/templates/default/success.html
{% extends 'default/base.html' %}


{% block content %}
    <section class="teachsetting" style="padding-bottom:40px;">
        <div class="container">
            <div class="regconfrimbox over-flow">
                <div class="confrimboxin bottomInput">
                    <h3 class="headdingformet">
                        <b style="font-size:25px;color:red;">Application Submitted</b>
                        <div class="backList">
                            <a href="{% url 'default:job-list' %}" class="btn greenbtn"
                               style="background: #fff none repeat scroll 0 0; border: 1px solid #1db95c;color: #1db95c;">&lt;
                                Back</a></div>
                    </h3>
                </div>
            </div>
        </div>
    </section>

{% endblock %}